---
title: "Video tutorials"
description: "This page hosts video tutorials for working with data using Google Sheets as well as instructions for submitting data-based assignments"
---


## Tutorial Library

Visit each of the links below to learn about how to conduct simple statistical analyses in Google Sheets. You will be expected to conduct these analyses in problem sets and exams. 

1. <a href="https://youtu.be/FIkZ1sPmKNw" target="_blank">Introduction to Google Sheets</a> [14 min]

2. <a href="https://drive.google.com/file/d/198UgYH2am7THaPztrXmS8GFQY3F4el-E/view?usp=sharing" target="_blank">Summarizing data </a> [32 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1gttiACvs_Hl6KUrPClquHqojyiR_tWvzNi6r7cQ_Sco/edit?usp=sharing)

3. <a href="https://drive.google.com/file/d/1xEqhRtPxg36sR297cu7vMwmAmwJkyVve/view?usp=drive_link" target="_blank">Central Tendencies </a> [16 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1zLSI3JOpme0AD-OBq6xPY_2kRSbG3eG_7vXCFnQZmfI/edit?usp=sharing)

4. <a href="https://drive.google.com/file/d/1y0jCn4Y3tU1wLQ_1g4rL8ow98d4gZJPU/view?usp=drive_link" target="_blank">Variability and z-scores </a> [8 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1tLnMaEC2yQvTvr6VeealI2ZKt7Mfly2DlD77chUxrho/edit?usp=sharing)

5. <a href="https://drive.google.com/file/d/12_c49z9-YW0FzYHgJAsMsYnWZASq189i/view?usp=drive_link" target="_blank">Pearson correlation </a> [10 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/10Qt8QBd-l6da4as99_5jtqqxVXfKs8yOI9qILnbiDFo/edit?usp=drive_link)

6. <a href="https://drive.google.com/file/d/1dSN9ng_7h9D-CltLEKZ68PGu178QAnUE/view?usp=drive_link" target="_blank">Linear regression </a> [8 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/10Qt8QBd-l6da4as99_5jtqqxVXfKs8yOI9qILnbiDFo/edit?usp=drive_link)

7. <a href="https://drive.google.com/file/d/1WUiPCeEvma1UtRRgccYZWkpOSA2nA7Ki/view?usp=drive_link" target="_blank">Spearman and point biserial correlations </a> [15 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/10Qt8QBd-l6da4as99_5jtqqxVXfKs8yOI9qILnbiDFo/edit?usp=drive_link)

8. <a href="https://drive.google.com/file/d/1xeFdH3wDgfJZ--BBmjQgIjIeNnnCl3i1/view?usp=sharing" target="_blank">Hypothesis Testing (Pearson correlation: t-test) </a> [8 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1FpF26OTQ5wWNIWKfUGxjNnhp7k46Cl6QS1UTaEklxQA/edit?usp=sharing)

9. <a href="https://drive.google.com/file/d/1SCGHcyaPTyodO8yOl3TvUU5m-HmJ50PD/view?usp=sharing" target="_blank"> Hypothesis Testing (Linear regression: t-test) </a> [14 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1FpF26OTQ5wWNIWKfUGxjNnhp7k46Cl6QS1UTaEklxQA/edit?usp=sharing)

10. <a href="https://drive.google.com/file/d/1ynV0050sH3nLTdXqBjMGGw0NzXQgKcAC/view?usp=drive_link" target="_blank">Hypothesis Testing (Linear regression: F-test) </a> [13.5 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1FpF26OTQ5wWNIWKfUGxjNnhp7k46Cl6QS1UTaEklxQA/edit?usp=sharing)

11. <a href="https://drive.google.com/file/d/15N2JiDs8FTGL83B1Ker0xwnsE_vbBR7b/view?usp=drive_link" target="_blank">Hypothesis Testing (two-groups: t-test) </a> [11 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1sLI5W5TJsfbE43uBtnn8CvSSxYMi-TEMTZ8eeot_ymc/edit?usp=sharing)

12. <a href="https://drive.google.com/file/d/1Wg1vFdzJoxUUnXn9F-O-h5HhsKSUg6Ek/view?usp=drive_link" target="_blank">Hypothesis Testing (two-groups: F-test) </a> [12 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1sLI5W5TJsfbE43uBtnn8CvSSxYMi-TEMTZ8eeot_ymc/edit?usp=sharing)

13. <a href="https://drive.google.com/file/d/1vTOd9K0wxKDy7s1YmsIaTC-FE3dxtzjr/view?usp=sharing" target="_blank">Hypothesis Testing (one-way ANOVA: F-test) </a> [18 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1y-QYZo_ECkmbpYPvOkgzrWmlglbzP3A5E7YdJbWZutM/edit?usp=drive_link)

14. <a href="https://drive.google.com/file/d/1udtNFQMpI53oQKv5b8-5Cujm1Xry-ONG/view?usp=sharing" target="_blank">Completing F tables </a> [8 min]

15. <a href="https://drive.google.com/file/d/1aDFkG_VUMJUEkNoE0Y21XhAZgD7yLU6W/view?usp=sharing" target="_blank">Factorial ANOVA </a> [33 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1cZYeVF1hO5bgklITBCxFZgXuU_olaD9QmhgPRkRuPNc/edit?usp=sharing)

16. <a href="https://drive.google.com/file/d/1uOQEaG6Y8qtFtL7dzvkmQf9EwgOI-sU1/view?usp=sharing" target="_blank">Dependent Groups t-test </a> [6 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1D6vnu9QXpcavVchUgVSYapY9pi6O49cmDZr92YxXhJo/edit?usp=sharing)

17. <a href="https://drive.google.com/file/d/1UzjppvZhRpoOlARZv01KiSG1RuKo97dU/view?usp=drive_link" target="_blank">Repeated Measures ANOVA </a> [16 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/1pLwb9_jb80ldLOBQfY0CdOyQ1foMUb8nh7_g3fSpghY/edit?usp=sharing)

18. <a href="https://drive.google.com/file/d/1wlatMsrdIqa3tfGPCwIw9Vma-ygRdQg0/view?usp=sharing" target="_blank">Chi-square Goodness of Fit Test </a> [13 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/19dq0aATbCrN7zQGfgGqQR1fjO5Gn1M709LJzacOh6kg/edit?usp=sharing)

19. <a href="https://drive.google.com/file/d/1O7ecae2KLkrBCceNmuTMGz7TVBNRyD04/view?usp=drive_link" target="_blank">Chi-square Test of Independence </a> [11 min] [[Sheets solution]](https://docs.google.com/spreadsheets/d/19dq0aATbCrN7zQGfgGqQR1fjO5Gn1M709LJzacOh6kg/edit?usp=sharing)

## Submitting assignments

For all problem sets or exams you complete in this course, you will be provided small to medium-sized datasets that you will need to conduct a set of analyses on using Google Sheets. The videos on this page will help you conduct these analyses as well as guide you through the process of submission from start to finish.

1. <a href="https://drive.google.com/file/d/1RSw1uhTpQPCSF77SMWHRw55DCNkIvoAD/view?usp=drive_link" target="_blank">Submitting a problem set</a>
  - This video describes how to submit an initial attempt for a problem set. Please watch it carefully before your first assignment so that you follow all the guidelines. 
  - Below is a checklist that you should go through BEFORE you submit any assignment/exam:
    - Copy over the solution template and edit it with your answers and explanations. Solution sheets should be brief and only mention numerical answers or provide brief explanations. They do not need to show any calculations - all calculations should be done in your worksheet. However, please explain the *process* behing the calculations, i.e., the order of operations should be clearly explained in the solution sheet.
    - Provide a link to the worksheet with ALL your calculations at the TOP of your solution sheet. Each question that includes any calculations should have a separate "sheet"/"tab" in your worksheet.
    - Make sure that the link you have provided opens up in an INCOGNITO tab without logging into any email.

2. <a href="https://drive.google.com/file/d/1DwWZlpevgR2F5XBmdBt9kAZGQepkrHyo/view?usp=drive_link" target="_blank">Revising a problem set</a>
  - This video describes how to revise an initial attempt for a problem set. 
  - Please make sure you indicate your revisions/corrections in PURPLE as shown in the video. 
  - Your new worksheet should only contain calculations that were incorrect or needed to be revised. 
<!--
3. Submitting an exam
  - This video describes how to submit the computational portion of an exam in this course. Please watch it carefully before your first midterm so that you follow all the guidelines. 
!-->


