---
title: "data-notebook"
output: html_document
date: "2024-01-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# packages

```{r}
library(tidyverse)
library(ggplot2)
library(lme4)
library(ggthemes)
```

# sleepstudy RT dataset

```{r}
sleepstudy %>%
  ggplot(aes(x=Days, y = Reaction))+
  geom_smooth(method="lm", aes(group = Subject))

write.csv(sleepstudy, file = "datasets/sleepRT.csv", row.names = FALSE)

lm_model = lm(data = sleepstudy, Reaction ~ Days)
summary(lm_model)

rt_model = lmer(data = sleepstudy, Reaction ~ Days + (1 | Subject))
summary(rt_model)
rt_coefs = ranef(rt_model)$Subject

p1 = sleepstudy %>% filter(Subject ==308)
p1m = lm(data = p1, Reaction ~ Days)
summary(p1m)
```


# sleep dataset

```{r}
sleepdata = read_csv("datasets/sleep.csv") %>% mutate(Patient = as.factor(Patient))

sleepdata %>%
  ggplot(aes(x=drug, y = sleep_increase))+
  #geom_point()+
  geom_line(aes(group = Patient, color = Patient))+
  theme_clean()+
  # geom_point(data = sleepdata %>% group_by(drug) %>% summarize(sleep_increase = mean(sleep_increase)),
  #            fill = "red", shape = 21, size = 5)+
  geom_text(aes(label = Patient))
  theme(legend.position = "none")


sleep_model = lmer(data = sleepdata, sleep_increase ~ drug + (1|Patient))
summary(sleep_model)
coefs = coef(sleep_model)
coefs

drugA = sleepdata %>% filter(drug == "A")
drugB = sleepdata %>% filter(drug == "B")
t.test(drugA$sleep_increase, drugB$sleep_increase, paired = TRUE)
```



